# Generated by Django 5.0.4 on 2024-04-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_dadosmedico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='descriacao',
            new_name='descricao',
        ),
    ]
